/**
 * Bundle the cross-agent MCP bridges into self-contained files.
 *
 *   node scripts/build-bridge.mjs
 *
 * Output: bridge-dist/gemini-bridge.mjs and bridge-dist/share-bridge.mjs, which
 * electron-builder ships as resources/bridge — see electron-builder.yml,
 * electron/bridge/mcp-config.ts and electron/bridge/share-mcp.ts.
 *
 * Why this exists: a bridge is not imported by Forge, it is *spawned* — an agent
 * CLI runs `node <path>` on it, from that agent's own working directory. In a
 * packaged app there is no node_modules anywhere above resources/bridge, so
 * `import '@modelcontextprotocol/sdk/...'` would fail at startup and the pane
 * would silently lose the bridge. Shipping the SDK's node_modules tree instead
 * would mean tracking its transitive dependencies by hand; one bundled file
 * cannot go stale.
 *
 * Two entries rather than one server with nine tools, and the reason is in
 * bridge/share-bridge.mjs's header: the Gemini bridge's environment carries an
 * API key and goes to Claude alone, while the share bridge carries no key and is
 * registered with four vendors. Bundling them separately is what keeps that true.
 *
 * Node built-ins stay external — they are supplied by the `node` that runs it.
 */
import { build } from 'esbuild'
import { mkdirSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const OUT_DIR = join(ROOT, 'bridge-dist')
const ENTRIES = ['gemini-bridge.mjs', 'share-bridge.mjs']

mkdirSync(OUT_DIR, { recursive: true })

for (const name of ENTRIES) {
  const out = join(OUT_DIR, name)
  await build({
    entryPoints: [join(ROOT, 'bridge', name)],
    outfile: out,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    // Not minified on purpose: if one of these misbehaves inside somebody's
    // agent pane, the stack trace should name real functions.
    minify: false,
    // No shebang here: esbuild hoists the entry's own `#!/usr/bin/env node` to
    // line 1, and a second one two lines down is a syntax error.
    banner: {
      js: `/* Generated by scripts/build-bridge.mjs — edit bridge/${name} instead. */`
    },
    logLevel: 'warning'
  })
  console.log(`  ok   bridge bundled — ${out} (${(statSync(out).size / 1024).toFixed(0)} KB)`)
}
