/**
 * Bundle the cross-agent MCP bridge into one self-contained file.
 *
 *   node scripts/build-bridge.mjs
 *
 * Output: bridge-dist/gemini-bridge.mjs, which electron-builder ships as
 * resources/bridge — see electron-builder.yml and electron/bridge/mcp-config.ts.
 *
 * Why this exists: the bridge is not imported by Forge, it is *spawned* —
 * Claude Code runs `node <path>` on it, from Claude's own working directory. In
 * a packaged app there is no node_modules anywhere above resources/bridge, so
 * `import '@modelcontextprotocol/sdk/...'` would fail at startup and the pane
 * would silently lose the bridge. Shipping the SDK's node_modules tree instead
 * would mean tracking its transitive dependencies by hand; one bundled file
 * cannot go stale.
 *
 * Node built-ins stay external — they are supplied by the `node` that runs it.
 */
import { build } from 'esbuild'
import { mkdirSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const ENTRY = join(ROOT, 'bridge', 'gemini-bridge.mjs')
const OUT_DIR = join(ROOT, 'bridge-dist')
const OUT = join(OUT_DIR, 'gemini-bridge.mjs')

mkdirSync(OUT_DIR, { recursive: true })

await build({
  entryPoints: [ENTRY],
  outfile: OUT,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  // Not minified on purpose: if this thing misbehaves inside somebody's Claude
  // pane, the stack trace should name real functions.
  minify: false,
  // No shebang here: esbuild hoists the entry's own `#!/usr/bin/env node` to
  // line 1, and a second one two lines down is a syntax error.
  banner: {
    js: '/* Generated by scripts/build-bridge.mjs — edit bridge/gemini-bridge.mjs instead. */'
  },
  logLevel: 'warning'
})

console.log(`  ok   bridge bundled — ${OUT} (${(statSync(OUT).size / 1024).toFixed(0)} KB)`)
